// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/api/agent.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationRequest) Reset() {
	*x = AttestationRequest{}
	mi := &file_pkg_api_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequest) ProtoMessage() {}

func (x *AttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequest.ProtoReflect.Descriptor instead.
func (*AttestationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AttestationRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type AttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationResponse) Reset() {
	*x = AttestationResponse{}
	mi := &file_pkg_api_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponse) ProtoMessage() {}

func (x *AttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponse.ProtoReflect.Descriptor instead.
func (*AttestationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	VolumeUuid    string                 `protobuf:"bytes,2,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // 0 = latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_pkg_api_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{2}
}

func (x *KeyRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *KeyRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *KeyRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *KeyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type KeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrappedKey    []byte                 `protobuf:"bytes,1,opt,name=wrapped_key,json=wrappedKey,proto3" json:"wrapped_key,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	VaultKvPath   string                 `protobuf:"bytes,3,opt,name=vault_kv_path,json=vaultKvPath,proto3" json:"vault_kv_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_pkg_api_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{3}
}

func (x *KeyResponse) GetWrappedKey() []byte {
	if x != nil {
		return x.WrappedKey
	}
	return nil
}

func (x *KeyResponse) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *KeyResponse) GetVaultKvPath() string {
	if x != nil {
		return x.VaultKvPath
	}
	return ""
}

type PostImagingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DevicePath      string                 `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Serial          string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	CurrentPassword []byte                 `protobuf:"bytes,5,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewRecoveryKey  []byte                 `protobuf:"bytes,6,opt,name=new_recovery_key,json=newRecoveryKey,proto3" json:"new_recovery_key,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TpmEnrollment   *TPMEnrollment         `protobuf:"bytes,8,opt,name=tpm_enrollment,json=tpmEnrollment,proto3" json:"tpm_enrollment,omitempty"` // TPM keys for future attestation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostImagingRequest) Reset() {
	*x = PostImagingRequest{}
	mi := &file_pkg_api_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostImagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostImagingRequest) ProtoMessage() {}

func (x *PostImagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostImagingRequest.ProtoReflect.Descriptor instead.
func (*PostImagingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PostImagingRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *PostImagingRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PostImagingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PostImagingRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *PostImagingRequest) GetCurrentPassword() []byte {
	if x != nil {
		return x.CurrentPassword
	}
	return nil
}

func (x *PostImagingRequest) GetNewRecoveryKey() []byte {
	if x != nil {
		return x.NewRecoveryKey
	}
	return nil
}

func (x *PostImagingRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PostImagingRequest) GetTpmEnrollment() *TPMEnrollment {
	if x != nil {
		return x.TpmEnrollment
	}
	return nil
}

type PostImagingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wrapped       *WrappedKey            `protobuf:"bytes,1,opt,name=wrapped,proto3" json:"wrapped,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Volume        *Volume                `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostImagingResponse) Reset() {
	*x = PostImagingResponse{}
	mi := &file_pkg_api_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostImagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostImagingResponse) ProtoMessage() {}

func (x *PostImagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostImagingResponse.ProtoReflect.Descriptor instead.
func (*PostImagingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PostImagingResponse) GetWrapped() *WrappedKey {
	if x != nil {
		return x.Wrapped
	}
	return nil
}

func (x *PostImagingResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PostImagingResponse) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type WrappedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	VaultKvPath   string                 `protobuf:"bytes,3,opt,name=vault_kv_path,json=vaultKvPath,proto3" json:"vault_kv_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrappedKey) Reset() {
	*x = WrappedKey{}
	mi := &file_pkg_api_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrappedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrappedKey) ProtoMessage() {}

func (x *WrappedKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrappedKey.ProtoReflect.Descriptor instead.
func (*WrappedKey) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{6}
}

func (x *WrappedKey) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *WrappedKey) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *WrappedKey) GetVaultKvPath() string {
	if x != nil {
		return x.VaultKvPath
	}
	return ""
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_pkg_api_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Version) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	LuksUuid      string                 `protobuf:"bytes,2,opt,name=luks_uuid,json=luksUuid,proto3" json:"luks_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_pkg_api_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Volume) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Volume) GetLuksUuid() string {
	if x != nil {
		return x.LuksUuid
	}
	return ""
}

// TPM Attestation messages
type NonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceRequest) Reset() {
	*x = NonceRequest{}
	mi := &file_pkg_api_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceRequest) ProtoMessage() {}

func (x *NonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceRequest.ProtoReflect.Descriptor instead.
func (*NonceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{9}
}

func (x *NonceRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

type NonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceResponse) Reset() {
	*x = NonceResponse{}
	mi := &file_pkg_api_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceResponse) ProtoMessage() {}

func (x *NonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceResponse.ProtoReflect.Descriptor instead.
func (*NonceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{10}
}

func (x *NonceResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *NonceResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AttestationKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeUuid    string                 `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Quote         *TPMQuote              `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	AkPublic      []byte                 `protobuf:"bytes,4,opt,name=ak_public,json=akPublic,proto3" json:"ak_public,omitempty"` // Attestation Key public key (for verification)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationKeyRequest) Reset() {
	*x = AttestationKeyRequest{}
	mi := &file_pkg_api_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationKeyRequest) ProtoMessage() {}

func (x *AttestationKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationKeyRequest.ProtoReflect.Descriptor instead.
func (*AttestationKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AttestationKeyRequest) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *AttestationKeyRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AttestationKeyRequest) GetQuote() *TPMQuote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *AttestationKeyRequest) GetAkPublic() []byte {
	if x != nil {
		return x.AkPublic
	}
	return nil
}

type TPMQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         []byte                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`         // TPM2B_ATTEST structure
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // TPMT_SIGNATURE structure
	Pcrs          []*PCRValue            `protobuf:"bytes,3,rep,name=pcrs,proto3" json:"pcrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TPMQuote) Reset() {
	*x = TPMQuote{}
	mi := &file_pkg_api_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPMQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPMQuote) ProtoMessage() {}

func (x *TPMQuote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPMQuote.ProtoReflect.Descriptor instead.
func (*TPMQuote) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TPMQuote) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *TPMQuote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TPMQuote) GetPcrs() []*PCRValue {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

type PCRValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCRValue) Reset() {
	*x = PCRValue{}
	mi := &file_pkg_api_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCRValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCRValue) ProtoMessage() {}

func (x *PCRValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCRValue.ProtoReflect.Descriptor instead.
func (*PCRValue) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PCRValue) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PCRValue) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// TPM enrollment during postimaging
type TPMEnrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EkPublic      []byte                 `protobuf:"bytes,1,opt,name=ek_public,json=ekPublic,proto3" json:"ek_public,omitempty"` // Endorsement Key public
	EkCert        []byte                 `protobuf:"bytes,2,opt,name=ek_cert,json=ekCert,proto3" json:"ek_cert,omitempty"`       // EK certificate (if available)
	AkPublic      []byte                 `protobuf:"bytes,3,opt,name=ak_public,json=akPublic,proto3" json:"ak_public,omitempty"` // Attestation Key public
	AkName        []byte                 `protobuf:"bytes,4,opt,name=ak_name,json=akName,proto3" json:"ak_name,omitempty"`       // AK name (for credential activation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TPMEnrollment) Reset() {
	*x = TPMEnrollment{}
	mi := &file_pkg_api_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPMEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPMEnrollment) ProtoMessage() {}

func (x *TPMEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPMEnrollment.ProtoReflect.Descriptor instead.
func (*TPMEnrollment) Descriptor() ([]byte, []int) {
	return file_pkg_api_agent_proto_rawDescGZIP(), []int{14}
}

func (x *TPMEnrollment) GetEkPublic() []byte {
	if x != nil {
		return x.EkPublic
	}
	return nil
}

func (x *TPMEnrollment) GetEkCert() []byte {
	if x != nil {
		return x.EkCert
	}
	return nil
}

func (x *TPMEnrollment) GetAkPublic() []byte {
	if x != nil {
		return x.AkPublic
	}
	return nil
}

func (x *TPMEnrollment) GetAkName() []byte {
	if x != nil {
		return x.AkName
	}
	return nil
}

var File_pkg_api_agent_proto protoreflect.FileDescriptor

const file_pkg_api_agent_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/api/agent.proto\x12\x03api\"J\n" +
	"\x12AttestationRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\"+\n" +
	"\x13AttestationResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"{\n" +
	"\n" +
	"KeyRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vvolume_uuid\x18\x02 \x01(\tR\n" +
	"volumeUuid\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"s\n" +
	"\vKeyResponse\x12\x1f\n" +
	"\vwrapped_key\x18\x01 \x01(\fR\n" +
	"wrappedKey\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\x05R\n" +
	"keyVersion\x12\"\n" +
	"\rvault_kv_path\x18\x03 \x01(\tR\vvaultKvPath\"\x8d\x03\n" +
	"\x12PostImagingRequest\x12\x1f\n" +
	"\vdevice_path\x18\x01 \x01(\tR\n" +
	"devicePath\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\x12)\n" +
	"\x10current_password\x18\x05 \x01(\fR\x0fcurrentPassword\x12(\n" +
	"\x10new_recovery_key\x18\x06 \x01(\fR\x0enewRecoveryKey\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.api.PostImagingRequest.LabelsEntryR\x06labels\x129\n" +
	"\x0etpm_enrollment\x18\b \x01(\v2\x12.api.TPMEnrollmentR\rtpmEnrollment\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x13PostImagingResponse\x12)\n" +
	"\awrapped\x18\x01 \x01(\v2\x0f.api.WrappedKeyR\awrapped\x12&\n" +
	"\aversion\x18\x02 \x01(\v2\f.api.VersionR\aversion\x12#\n" +
	"\x06volume\x18\x03 \x01(\v2\v.api.VolumeR\x06volume\"q\n" +
	"\n" +
	"WrappedKey\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\x05R\n" +
	"keyVersion\x12\"\n" +
	"\rvault_kv_path\x18\x03 \x01(\tR\vvaultKvPath\"\x1f\n" +
	"\aVersion\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"9\n" +
	"\x06Volume\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tluks_uuid\x18\x02 \x01(\tR\bluksUuid\"/\n" +
	"\fNonceRequest\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\"D\n" +
	"\rNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x90\x01\n" +
	"\x15AttestationKeyRequest\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12#\n" +
	"\x05quote\x18\x03 \x01(\v2\r.api.TPMQuoteR\x05quote\x12\x1b\n" +
	"\tak_public\x18\x04 \x01(\fR\bakPublic\"a\n" +
	"\bTPMQuote\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\fR\x05quote\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12!\n" +
	"\x04pcrs\x18\x03 \x03(\v2\r.api.PCRValueR\x04pcrs\"8\n" +
	"\bPCRValue\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"{\n" +
	"\rTPMEnrollment\x12\x1b\n" +
	"\tek_public\x18\x01 \x01(\fR\bekPublic\x12\x17\n" +
	"\aek_cert\x18\x02 \x01(\fR\x06ekCert\x12\x1b\n" +
	"\tak_public\x18\x03 \x01(\fR\bakPublic\x12\x17\n" +
	"\aak_name\x18\x04 \x01(\fR\x06akName2\xf9\x01\n" +
	"\vLuksManager\x12=\n" +
	"\x06Attest\x12\x17.api.AttestationRequest\x1a\x18.api.AttestationResponse\"\x00\x12-\n" +
	"\x06GetKey\x12\x0f.api.KeyRequest\x1a\x10.api.KeyResponse\"\x00\x123\n" +
	"\bGetNonce\x12\x11.api.NonceRequest\x1a\x12.api.NonceResponse\"\x00\x12G\n" +
	"\x15GetKeyWithAttestation\x12\x1a.api.AttestationKeyRequest\x1a\x10.api.KeyResponse\"\x002R\n" +
	"\fAgentService\x12B\n" +
	"\vPostImaging\x12\x17.api.PostImagingRequest\x1a\x18.api.PostImagingResponse\"\x00B\x12Z\x10rootseal/pkg/apib\x06proto3"

var (
	file_pkg_api_agent_proto_rawDescOnce sync.Once
	file_pkg_api_agent_proto_rawDescData []byte
)

func file_pkg_api_agent_proto_rawDescGZIP() []byte {
	file_pkg_api_agent_proto_rawDescOnce.Do(func() {
		file_pkg_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_agent_proto_rawDesc), len(file_pkg_api_agent_proto_rawDesc)))
	})
	return file_pkg_api_agent_proto_rawDescData
}

var file_pkg_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_api_agent_proto_goTypes = []any{
	(*AttestationRequest)(nil),    // 0: api.AttestationRequest
	(*AttestationResponse)(nil),   // 1: api.AttestationResponse
	(*KeyRequest)(nil),            // 2: api.KeyRequest
	(*KeyResponse)(nil),           // 3: api.KeyResponse
	(*PostImagingRequest)(nil),    // 4: api.PostImagingRequest
	(*PostImagingResponse)(nil),   // 5: api.PostImagingResponse
	(*WrappedKey)(nil),            // 6: api.WrappedKey
	(*Version)(nil),               // 7: api.Version
	(*Volume)(nil),                // 8: api.Volume
	(*NonceRequest)(nil),          // 9: api.NonceRequest
	(*NonceResponse)(nil),         // 10: api.NonceResponse
	(*AttestationKeyRequest)(nil), // 11: api.AttestationKeyRequest
	(*TPMQuote)(nil),              // 12: api.TPMQuote
	(*PCRValue)(nil),              // 13: api.PCRValue
	(*TPMEnrollment)(nil),         // 14: api.TPMEnrollment
	nil,                           // 15: api.PostImagingRequest.LabelsEntry
}
var file_pkg_api_agent_proto_depIdxs = []int32{
	15, // 0: api.PostImagingRequest.labels:type_name -> api.PostImagingRequest.LabelsEntry
	14, // 1: api.PostImagingRequest.tpm_enrollment:type_name -> api.TPMEnrollment
	6,  // 2: api.PostImagingResponse.wrapped:type_name -> api.WrappedKey
	7,  // 3: api.PostImagingResponse.version:type_name -> api.Version
	8,  // 4: api.PostImagingResponse.volume:type_name -> api.Volume
	12, // 5: api.AttestationKeyRequest.quote:type_name -> api.TPMQuote
	13, // 6: api.TPMQuote.pcrs:type_name -> api.PCRValue
	0,  // 7: api.LuksManager.Attest:input_type -> api.AttestationRequest
	2,  // 8: api.LuksManager.GetKey:input_type -> api.KeyRequest
	9,  // 9: api.LuksManager.GetNonce:input_type -> api.NonceRequest
	11, // 10: api.LuksManager.GetKeyWithAttestation:input_type -> api.AttestationKeyRequest
	4,  // 11: api.AgentService.PostImaging:input_type -> api.PostImagingRequest
	1,  // 12: api.LuksManager.Attest:output_type -> api.AttestationResponse
	3,  // 13: api.LuksManager.GetKey:output_type -> api.KeyResponse
	10, // 14: api.LuksManager.GetNonce:output_type -> api.NonceResponse
	3,  // 15: api.LuksManager.GetKeyWithAttestation:output_type -> api.KeyResponse
	5,  // 16: api.AgentService.PostImaging:output_type -> api.PostImagingResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_api_agent_proto_init() }
func file_pkg_api_agent_proto_init() {
	if File_pkg_api_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_agent_proto_rawDesc), len(file_pkg_api_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_api_agent_proto_goTypes,
		DependencyIndexes: file_pkg_api_agent_proto_depIdxs,
		MessageInfos:      file_pkg_api_agent_proto_msgTypes,
	}.Build()
	File_pkg_api_agent_proto = out.File
	file_pkg_api_agent_proto_goTypes = nil
	file_pkg_api_agent_proto_depIdxs = nil
}
