// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: pkg/api/agent.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LuksManager_Attest_FullMethodName                = "/api.LuksManager/Attest"
	LuksManager_GetKey_FullMethodName                = "/api.LuksManager/GetKey"
	LuksManager_GetNonce_FullMethodName              = "/api.LuksManager/GetNonce"
	LuksManager_GetKeyWithAttestation_FullMethodName = "/api.LuksManager/GetKeyWithAttestation"
)

// LuksManagerClient is the client API for LuksManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LuksManagerClient interface {
	Attest(ctx context.Context, in *AttestationRequest, opts ...grpc.CallOption) (*AttestationResponse, error)
	GetKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KeyResponse, error)
	// TPM attestation flow
	GetNonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error)
	GetKeyWithAttestation(ctx context.Context, in *AttestationKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error)
}

type luksManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewLuksManagerClient(cc grpc.ClientConnInterface) LuksManagerClient {
	return &luksManagerClient{cc}
}

func (c *luksManagerClient) Attest(ctx context.Context, in *AttestationRequest, opts ...grpc.CallOption) (*AttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestationResponse)
	err := c.cc.Invoke(ctx, LuksManager_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luksManagerClient) GetKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, LuksManager_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luksManagerClient) GetNonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NonceResponse)
	err := c.cc.Invoke(ctx, LuksManager_GetNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luksManagerClient) GetKeyWithAttestation(ctx context.Context, in *AttestationKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, LuksManager_GetKeyWithAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuksManagerServer is the server API for LuksManager service.
// All implementations must embed UnimplementedLuksManagerServer
// for forward compatibility.
type LuksManagerServer interface {
	Attest(context.Context, *AttestationRequest) (*AttestationResponse, error)
	GetKey(context.Context, *KeyRequest) (*KeyResponse, error)
	// TPM attestation flow
	GetNonce(context.Context, *NonceRequest) (*NonceResponse, error)
	GetKeyWithAttestation(context.Context, *AttestationKeyRequest) (*KeyResponse, error)
	mustEmbedUnimplementedLuksManagerServer()
}

// UnimplementedLuksManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLuksManagerServer struct{}

func (UnimplementedLuksManagerServer) Attest(context.Context, *AttestationRequest) (*AttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedLuksManagerServer) GetKey(context.Context, *KeyRequest) (*KeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedLuksManagerServer) GetNonce(context.Context, *NonceRequest) (*NonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonce not implemented")
}
func (UnimplementedLuksManagerServer) GetKeyWithAttestation(context.Context, *AttestationKeyRequest) (*KeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyWithAttestation not implemented")
}
func (UnimplementedLuksManagerServer) mustEmbedUnimplementedLuksManagerServer() {}
func (UnimplementedLuksManagerServer) testEmbeddedByValue()                     {}

// UnsafeLuksManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LuksManagerServer will
// result in compilation errors.
type UnsafeLuksManagerServer interface {
	mustEmbedUnimplementedLuksManagerServer()
}

func RegisterLuksManagerServer(s grpc.ServiceRegistrar, srv LuksManagerServer) {
	// If the following call pancis, it indicates UnimplementedLuksManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LuksManager_ServiceDesc, srv)
}

func _LuksManager_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuksManagerServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuksManager_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuksManagerServer).Attest(ctx, req.(*AttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuksManager_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuksManagerServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuksManager_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuksManagerServer).GetKey(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuksManager_GetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuksManagerServer).GetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuksManager_GetNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuksManagerServer).GetNonce(ctx, req.(*NonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuksManager_GetKeyWithAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuksManagerServer).GetKeyWithAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuksManager_GetKeyWithAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuksManagerServer).GetKeyWithAttestation(ctx, req.(*AttestationKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LuksManager_ServiceDesc is the grpc.ServiceDesc for LuksManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LuksManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LuksManager",
	HandlerType: (*LuksManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attest",
			Handler:    _LuksManager_Attest_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _LuksManager_GetKey_Handler,
		},
		{
			MethodName: "GetNonce",
			Handler:    _LuksManager_GetNonce_Handler,
		},
		{
			MethodName: "GetKeyWithAttestation",
			Handler:    _LuksManager_GetKeyWithAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/agent.proto",
}

const (
	AgentService_PostImaging_FullMethodName = "/api.AgentService/PostImaging"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	PostImaging(ctx context.Context, in *PostImagingRequest, opts ...grpc.CallOption) (*PostImagingResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) PostImaging(ctx context.Context, in *PostImagingRequest, opts ...grpc.CallOption) (*PostImagingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostImagingResponse)
	err := c.cc.Invoke(ctx, AgentService_PostImaging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	PostImaging(context.Context, *PostImagingRequest) (*PostImagingResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) PostImaging(context.Context, *PostImagingRequest) (*PostImagingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostImaging not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_PostImaging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostImagingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PostImaging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PostImaging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PostImaging(ctx, req.(*PostImagingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostImaging",
			Handler:    _AgentService_PostImaging_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/agent.proto",
}
